### ISSUE TITLE
I couldn't sign in 

### ISSUE THREAD

**Issue by MohamedYassineAbid** [MohamedAliJmal/Matrix_Manipulator#14]
![Screenshot from 2024-11-08 23-34-27](https://github.com/user-attachments/assets/92ed4fe6-3911-48c5-ba60-513e7d8a6ee3)

**Comment by MohamedAliJmal** [comment]
problem solved
![image](https://github.com/user-attachments/assets/386d2468-7539-410f-94af-d4365f8a3a9d)
